name: pocket_bus
description: Pocket Bus.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.4+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  intl: ^0.15.8
  http: ^0.12.0+2
  rxdart: ^0.22.2
  share: ^0.6.2+1
  connectivity: ^0.4.4
  flutter_local_notifications: ^0.8.2+1
  geolocator: ^5.1.3
  package_info: ^0.4.0+6
  app_settings: ^1.0.6+2
  rect_getter: ^0.0.1

  flare_flutter: ^1.5.8
  url_launcher: ^5.1.2
  launch_review: ^2.0.0
  google_maps_flutter:
    git:
      url: git://github.com/klausjokinen/plugins/
      path: packages/google_maps_flutter
      ref: development
#  google_maps_flutter: ^0.4.0
#  google_maps_flutter:
#    path: ./_packages/google_maps_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2



# For generating iOS Icons.
flutter_icons:
#  android: "launcher_icon"
  android: true
  ios: true
  image_path: "images/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/
    - api.keys


  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Bold.ttf
    - asset: fonts/Montserrat-Regular.ttf